arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - ur5_arm_shoulder_pan_joint
    - ur5_arm_shoulder_lift_joint
    - ur5_arm_elbow_joint
    - ur5_arm_wrist_1_joint
    - ur5_arm_wrist_2_joint
    - ur5_arm_wrist_3_joint
  gains:
    ur5_arm_shoulder_pan_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ur5_arm_shoulder_lift_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ur5_arm_elbow_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ur5_arm_wrist_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ur5_arm_wrist_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ur5_arm_wrist_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - gripper_finger1_joint
  gains:
    gripper_finger1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1